SELECT DISTINCT 
				SMATRICULA.RA              AS RA,
                PPESSOA.NOME               AS ALUNO_NOME,
                FCFO.NOME                  AS FIN_NOME,
                SCONTRATO.CODCONTRATO      AS SCONTRATO_CODCONTRATO,
                SCONTRATO.ASSINADO         AS SCONTRATO_ASSINADO,
                SCONTRATO.CODFILIAL        AS SCONTRATO_CODFILIAL,
                GUSRPERFIL.CODCOLIGADA     AS GUSRPERFIL_CODCOLIGADA,
                SUSUARIOFILIAL.CODFILIAL   AS SUSUARIOFILIAL_FILIAL,
                GUSRPERFIL.CODPERFIL       AS GUSRPERFIL_CODPERFIL,
                GUSRPERFIL.CODSISTEMA      AS GUSPERFIL_CODSISTEMA
FROM   SMATRICULA (NOLOCK)
	   LEFT JOIN SALUNO (NOLOCK)
                      ON SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA
                         AND SMATRICULA.RA = SALUNO.RA                 
	   LEFT JOIN SCONTRATO (NOLOCK)
              ON SALUNO.CODCOLIGADA = SCONTRATO.CODCOLIGADA
                 AND SALUNO.RA = SCONTRATO.RA
 
       LEFT JOIN SMATRICPL (NOLOCK)
              ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
             AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
             AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
             AND SMATRICULA.RA = SMATRICPL.RA
             
       LEFT JOIN PPESSOA (NOLOCK)
              ON SALUNO.CODPESSOA = PPESSOA.CODIGO
       LEFT JOIN FCFO (NOLOCK)
              ON FCFO.CODCOLIGADA = SALUNO.CODCOLCFO
                 AND FCFO.CODCFO = SALUNO.CODCFO
       LEFT JOIN GUSUARIO (NOLOCK)
       		ON FCFO.CODUSUARIOACESSO = GUSUARIO.CODUSUARIO
       		
       LEFT JOIN SUSUARIOFILIAL (NOLOCK)
       		  ON GUSUARIO.CODUSUARIO = SUSUARIOFILIAL.CODUSUARIO
       LEFT JOIN GPERMIS (NOLOCK)
              ON GUSUARIO.CODUSUARIO = GPERMIS.CODUSUARIO
       LEFT JOIN GUSRPERFIL (NOLOCK)
       		  ON GUSUARIO.CODUSUARIO = GUSRPERFIL.CODUSUARIO
       		  
       LEFT JOIN SPLETIVO (NOLOCK)
              ON SCONTRATO.CODCOLIGADA = SPLETIVO.CODCOLIGADA
                 AND SCONTRATO.IDPERLET = SPLETIVO.IDPERLET
WHERE  SCONTRATO.CODCOLIGADA = :CODCOLIGADA
       AND SCONTRATO.CODFILIAL = :CODFILIAL
       AND SCONTRATO.IDPERLET= :IDPERLET
       /*AND SMATRICULA.CODSTATUS = 1 
       AND SMATRICPL.CODSTATUS = 1 */
GROUP BY
    SMATRICULA.RA,
    PPESSOA.NOME,
    SCONTRATO.CODCONTRATO,
    SCONTRATO.ASSINADO,
    SCONTRATO.CODFILIAL,
    GUSRPERFIL.CODCOLIGADA,
    GUSRPERFIL.CODPERFIL,
    GUSRPERFIL.CODSISTEMA,
    FCFO.NOME,
    SUSUARIOFILIAL.CODFILIAL