SELECT DISTINCT PPESSOA.NOME                                        AS NOME_ALUNO,
                SMATRICPL.RA                                        AS RA,
                SPLETIVO.CODPERLET                                  AS ANOLETIVO,
                SMATRICPL.CODTURMA                                  AS TURMA,
                CONVERT(VARCHAR(MAX), SALUNOFICHAMEDICA.ALERGIA)    AS ALERGIAS,
                CONVERT(VARCHAR(MAX), SALUNOFICHAMEDICA.MEDICO)     AS MEDICOS,
                CONVERT(VARCHAR(MAX), SALUNOFICHAMEDICA.REMEDIO)    AS REMEDIOS,
                CONVERT(VARCHAR(MAX), SALUNOFICHAMEDICA.TRATAMENTO) AS TRATAMENTOS,
                CONVERT(VARCHAR(MAX), SALUNOFICHAMEDICA.SOCHOSP)    AS SOC_HOSPITALAR,
                CONVERT(VARCHAR(MAX), SALUNOFICHAMEDICA.OUTRO)      AS OUTROS
FROM   SMATRICULA (NOLOCK)
       LEFT JOIN SALUNO (NOLOCK)
              ON SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA
                 AND SMATRICULA.RA = SALUNO.RA
       LEFT JOIN PPESSOA (NOLOCK)
              ON SALUNO.CODPESSOA = PPESSOA.CODIGO
       LEFT JOIN SMATRICPL (NOLOCK)
              ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
                 AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
                 AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
                 AND SMATRICULA.RA = SMATRICPL.RA
       LEFT JOIN STURMADISC (NOLOCK)
              ON SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
                 AND SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC
       LEFT JOIN SPLETIVO (NOLOCK)
              ON SMATRICULA.CODCOLIGADA = SPLETIVO.CODCOLIGADA
                 AND SMATRICULA.IDPERLET = SPLETIVO.IDPERLET
                 AND STURMADISC.CODFILIAL = SPLETIVO.CODFILIAL
       LEFT JOIN SALUNOFICHAMEDICA (NOLOCK)
              ON SALUNO.CODCOLIGADA = SALUNOFICHAMEDICA.CODCOLIGADA
                 AND SALUNO.RA = SALUNOFICHAMEDICA.RA
WHERE  SMATRICPL.CODCOLIGADA = :$CODCOLIGADA
       AND SMATRICPL.CODFILIAL = :CODFILIAL
       AND SMATRICULA.CODSTATUS = 1
       AND SMATRICPL.CODSTATUS = 1
       AND SPLETIVO.CODPERLET = :ANO_LETIVO
       AND SMATRICPL.RA LIKE ( :ALUNO_RA )
       AND SMATRICPL.CODTURMA LIKE Upper(:TURMA)
       AND STURMADISC.ATIVA = 'S' 
