SELECT*,

      ((ISNULL(P1,0 )+ ISNULL(PS_T1,0 )+ ISNULL(P2_T1,0)+ISNULL(REC_P1,0))/2) AS PARCIAL_T1,

      ((ISNULL(P1_T2,0) + ISNULL(PS_T2,0)+ ISNULL(P2_T2,0)+ISNULL(RECP1_T2,0))/2) AS PARCIAL_T2,

      ((ISNULL(P1_T3,0) + ISNULL(PS_T3,0)+ ISNULL(P2_T3,0)+ISNULL(RECP1_T3,0))/2) AS PARCIAL_T3
FROM (
	SELECT
       SDISCIPLINA.NOME             AS NOME_DISC,
       MAX(PERIODOLETIVO.CODPERLET) AS ANOLETIVO,
       SNOTAS.CODCOLIGADA,
       SNOTAS.IDTURMADISC,
       SNOTAS.RA,
       PPESSOA.NOME AS ALUNO_NOME,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3111 THEN SNOTAS.NOTA
           END)     AS P1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3112 THEN SNOTAS.NOTA
           END)     AS REC_P1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3113 THEN SNOTAS.NOTA
           END)     AS PS_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3114 THEN SNOTAS.NOTA
           END)     AS P2_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3121 THEN SNOTAS.NOTA
           END)     AS REC_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3211 THEN SNOTAS.NOTA
           END)     AS P1_T2,
       
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3212 THEN SNOTAS.NOTA
           END)     AS RECP1_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3213 THEN SNOTAS.NOTA
           END)     AS PS_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3214 THEN SNOTAS.NOTA
           END)     AS P2_T2,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 3221 THEN SNOTAS.NOTA
           END)     AS REC_T2,
           
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3311 THEN SNOTAS.NOTA
           END)     AS P1_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3312 THEN SNOTAS.NOTA
           END)     AS RECP1_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3313 THEN SNOTAS.NOTA
           END)     AS PS_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3314 THEN SNOTAS.NOTA
           END)     AS P2_T3,
 
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3321 THEN SNOTAS.NOTA
           END)     AS REC_T3
      
FROM SMATRICULA (NOLOCK)

        LEFT JOIN STURMADISC (NOLOCK)
            ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
            AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC

        LEFT JOIN SALUNO (NOLOCK)
            ON SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA
            AND SMATRICULA.RA = SALUNO.RA

        LEFT JOIN PPESSOA (NOLOCK)
            ON SALUNO.CODPESSOA = PPESSOA.CODIGO

        LEFT JOIN SNOTAS (NOLOCK)
            ON SNOTAS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
            AND SNOTAS.IDTURMADISC = SMATRICULA.IDTURMADISC
            AND SNOTAS.RA = SMATRICULA.RA

        LEFT JOIN SPROVAS (NOLOCK)
            ON SNOTAS.CODPROVA = SPROVAS.CODPROVA
            AND SNOTAS.IDTURMADISC = SPROVAS.IDTURMADISC
            AND SNOTAS.CODETAPA = SPROVAS.CODETAPA
            AND SNOTAS.TIPOETAPA = SPROVAS.TIPOETAPA
            AND SNOTAS.CODCOLIGADA = SPROVAS.CODCOLIGADA

        LEFT JOIN SDISCIPLINA (NOLOCK)
            ON SDISCIPLINA.CODDISC = STURMADISC.CODDISC
            AND SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
        LEFT JOIN SPLETIVO PERIODOLETIVO (NOLOCK)
            ON PERIODOLETIVO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
            AND PERIODOLETIVO.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.CODCOLIGADA = :COLIGADA
        AND SMATRICULA.IDTURMADISC = :IDTURMADISC
        AND STURMADISC.CODDISC = :CODDISC
GROUP  BY SNOTAS.CODCOLIGADA,
          SNOTAS.IDTURMADISC,
          PPESSOA.NOME,
          SNOTAS.RA,
          STURMADISC.CODDISC,
          SDISCIPLINA.NOME 
)p