SELECT 
       SDISCIPLINA.NOME             AS NOME_DISC
       SNOTAS.CODCOLIGADA,
       SNOTAS.IDTURMADISC,
       SNOTAS.RA,
       PPESSOA.NOME AS ALUNO_NOME,

       /*FUND I*/
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2111 THEN SNOTAS.NOTA
           END)     AS P1_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2112 THEN SNOTAS.NOTA
           END)     AS P2_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2113 THEN SNOTAS.NOTA
           END)     AS AD1_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2114 THEN SNOTAS.NOTA
           END)     AS AD2_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2115 THEN SNOTAS.NOTA
           END)     AS PARTICIP_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2116 THEN SNOTAS.NOTA
           END)     AS TAREFA_T1,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 2121 THEN SNOTAS.NOTA
           END)     AS REC_T1,
       SUM(ISNULL(P1_T1,0) + ISNULL(P2_T1,0) + ISNULL(AD1_T1,0) + ISNULL(AD2_T1,0) + ISNULL(PARTICIP_T1,0) + ISNULL(TAREFA_T1,0) + ISNULL(REC_T1,0)/2) AS PARCIAL_T1,


      Max(CASE
             WHEN SNOTAS.CODPROVA = 2211 THEN SNOTAS.NOTA
           END)     AS P1_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2212 THEN SNOTAS.NOTA
           END)     AS P2_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2213 THEN SNOTAS.NOTA
           END)     AS AD1_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2214 THEN SNOTAS.NOTA
           END)     AS AD2_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2215 THEN SNOTAS.NOTA
           END)     AS PARTICIP_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2216 THEN SNOTAS.NOTA
           END)     AS TAREFA_T2,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 2221 THEN SNOTAS.NOTA
           END)     AS REC_T2,

       SUM(ISNULL(P1_T2,0) + ISNULL(P2_T2,0) + ISNULL(AD1_T2,0) + ISNULL(AD2_T2,0) + ISNULL(PARTICIP_T2,0) + ISNULL(TAREFA_T2,0) + ISNULL(REC_T2,0)/2) AS PARCIAL_T2,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 2311 THEN SNOTAS.NOTA
           END)     AS P1_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2312 THEN SNOTAS.NOTA
           END)     AS P2_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2313 THEN SNOTAS.NOTA
           END)     AS AD1_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2314 THEN SNOTAS.NOTA
           END)     AS AD2_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2315 THEN SNOTAS.NOTA
           END)     AS PARTICIP_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 2316 THEN SNOTAS.NOTA
           END)     AS TAREFA_T3,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 2321 THEN SNOTAS.NOTA
           END)     AS REC_T3,

      SUM(ISNULL(P1_T3,0) + ISNULL(P2_T3,0) + ISNULL(AD1_T3,0) + ISNULL(AD2_T3,0) + ISNULL(PARTICIP_T3,0) + ISNULL(TAREFA_T3,0) + ISNULL(REC_T3,0)/2) AS PARCIAL_T3,

      /*FUND II*/

      Max(CASE
             WHEN SNOTAS.CODPROVA = 3111 THEN SNOTAS.NOTA
           END)     AS EF2P1_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3112 THEN SNOTAS.NOTA
           END)     AS EF2P2_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3113 THEN SNOTAS.NOTA
           END)     AS EF2SIMULADO_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3114 THEN SNOTAS.NOTA
           END)     AS EF2AT_INDIV_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3115 THEN SNOTAS.NOTA
           END)     AS EF2TB1_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3116 THEN SNOTAS.NOTA
           END)     AS EF2TB2_T1,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3117 THEN SNOTAS.NOTA
           END)     AS EF2TB3_T1,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 3121 THEN SNOTAS.NOTA
           END)     AS EF2REC_T1,
       SUM(ISNULL(EF2P1_T1,0) + ISNULL(EF2P2_T1,0) + ISNULL(EF2SIMULADO_T1,0) + ISNULL(EF2AT_INDIV_T1,0) + ISNULL(EF2TB1_T1,0) + ISNULL(EF2TB2_T1,0) + ISNULL(EF2TB3_T1,0) + ISNULL(EF2REC_T1,0)/2) AS EF2PARCIAL_T1,

      Max(CASE
             WHEN SNOTAS.CODPROVA = 3211 THEN SNOTAS.NOTA
           END)     AS EF2P1_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3212 THEN SNOTAS.NOTA
           END)     AS EF2P2_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3213 THEN SNOTAS.NOTA
           END)     AS EF2SIMULADO_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3214 THEN SNOTAS.NOTA
           END)     AS EF2AT_INDIV_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3215 THEN SNOTAS.NOTA
           END)     AS EF2TB1_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3216 THEN SNOTAS.NOTA
           END)     AS EF2TB2_T2,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3217 THEN SNOTAS.NOTA
           END)     AS EF2TB3_T2,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 3221 THEN SNOTAS.NOTA
           END)     AS EF2REC_T2,

       SUM(ISNULL(EF2P1_T2,0) + ISNULL(EF2P2_T2,0) + ISNULL(EF2SIMULADO_T2,0) + ISNULL(EF2AT_INDIV_T2,0) + ISNULL(EF2TB1_T2,0) + ISNULL(EF2TB2_T2,0) + ISNULL(EF2TB3_T2,0) + ISNULL(EF2REC_T2,0)/2) AS EF2PARCIAL_T2,


       Max(CASE
             WHEN SNOTAS.CODPROVA = 3311 THEN SNOTAS.NOTA
           END)     AS EF2P1_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3312 THEN SNOTAS.NOTA
           END)     AS EF2P2_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3313 THEN SNOTAS.NOTA
           END)     AS EF2SIMULADO_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3314 THEN SNOTAS.NOTA
           END)     AS EF2AT_INDIV_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3315 THEN SNOTAS.NOTA
           END)     AS EF2TB1_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3316 THEN SNOTAS.NOTA
           END)     AS EF2TB2_T3,
       Max(CASE
             WHEN SNOTAS.CODPROVA = 3317 THEN SNOTAS.NOTA
           END)     AS EF2TB3_T3,

       Max(CASE
             WHEN SNOTAS.CODPROVA = 3321 THEN SNOTAS.NOTA
           END)     AS EF2REC_T3,

       SUM(ISNULL(EF2P1_T3,0) + ISNULL(EF2P2_T3,0) + ISNULL(EF2SIMULADO_T3,0) + ISNULL(EF2AT_INDIV_T3,0) + ISNULL(EF2TB1_T3,0) + ISNULL(EF2TB2_T3,0) + ISNULL(EF2TB3_T3,0) + ISNULL(EF2REC_T3,0)/2) AS EF2PARCIAL_T3,


FROM   SNOTAS (NOLOCK)
       LEFT JOIN SPROVAS (NOLOCK)
              ON SNOTAS.CODPROVA = SPROVAS.CODPROVA
                 AND SNOTAS.IDTURMADISC = SPROVAS.IDTURMADISC
                 AND SNOTAS.CODETAPA = SPROVAS.CODETAPA
                 AND SNOTAS.TIPOETAPA = SPROVAS.TIPOETAPA
                 AND SNOTAS.CODCOLIGADA = SPROVAS.CODCOLIGADA
       LEFT JOIN SMATRICULA (NOLOCK)
              ON SNOTAS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
                 AND SNOTAS.IDTURMADISC = SMATRICULA.IDTURMADISC
                 AND SNOTAS.RA = SMATRICULA.RA
       LEFT JOIN SALUNO (NOLOCK)
              ON SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA
                 AND SMATRICULA.RA = SALUNO.RA
       LEFT JOIN PPESSOA (NOLOCK)
              ON SALUNO.CODPESSOA = PPESSOA.CODIGO
       LEFT JOIN SPROFESSOR (NOLOCK)
              ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
       LEFT JOIN STURMADISC (NOLOCK)
              ON STURMADISC.CODCOLIGADA = SNOTAS.CODCOLIGADA
              AND STURMADISC.IDTURMADISC = SNOTAS.IDTURMADISC   
       LEFT JOIN SDISCIPLINA (NOLOCK)
            ON SDISCIPLINA.CODDISC = STURMADISC.CODDISC
            AND SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
WHERE  SNOTAS.CODCOLIGADA = :COLIGADA
       AND SNOTAS.IDTURMADISC = :IDTURMADISC
       AND STURMADISC.CODDISC = :CODDISC
GROUP  BY SNOTAS.CODCOLIGADA,
          SNOTAS.IDTURMADISC,
          PPESSOA.NOME,
          SNOTAS.RA,
          STURMADISC.CODDISC
