SELECT 
    STURMADISC.CODDISC                          AS NOME_DISC,
    SPLANOAULA.DATA                             AS AULA_DATA,
    FORMAT(SPLANOAULA.DATA, 'dddd', 'pt-BR')    AS DIA_SEMANA,
    SHORARIO.HORAINICIAL                        AS HORA_INICIO,
    SHORARIO.HORAFINAL                          AS HORA_FIM,              
    MAX(CAST(SPLANOAULA.CONTEUDOEFETIVO         AS VARCHAR(MAX))) AS CONTEUDO_EFET,
    MAX(CAST(SPLANOAULA.CONTEUDO                AS VARCHAR (MAX))) AS CONTEUDO,
    SMATRICPL.RA                                AS RA,
    PPESSOA.NOME                                AS NOME_ALUNO,

    /* Busca frequencia por data*/
    /* A tabela SFREQUENCIA registra apenas faltas (ausências) 'A'.
   A consulta verifica se existe registro do aluno:
   - Se NÃO houver registro → considera presença
   - Se houver registro → considera falta */
    COUNT(DISTINCT 
    CASE 
        WHEN SFREQUENCIA.RA IS NULL
        THEN CONCAT(SPLANOAULA.DATA, SPLANOAULA.IDHORARIOTURMA, SMATRICPL.RA)
    END) AS FREQUENCIA



FROM SPLANOAULA (NOLOCK)

    LEFT JOIN STURMADISC (NOLOCK)
        ON SPLANOAULA.IDTURMADISC = STURMADISC.IDTURMADISC
        AND SPLANOAULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SPLANOAULA.CODFILIAL = STURMADISC.CODFILIAL

    
    LEFT JOIN STURMA (NOLOCK)
        ON  STURMADISC.CODTURMA = STURMA.CODTURMA
        AND STURMADISC.IDPERLET = STURMA.IDPERLET 
        AND STURMADISC.CODCOLIGADA = STURMA.CODCOLIGADA
        AND STURMADISC.CODFILIAL = STURMA.CODFILIAL 
    
    LEFT JOIN SMATRICPL (NOLOCK)
        ON  STURMA.CODTURMA = SMATRICPL.CODTURMA 
        AND STURMA.IDPERLET = SMATRICPL.IDPERLET
        AND STURMA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
        AND STURMA.CODFILIAL = SMATRICPL.CODFILIAL

    /* BUSCA DATA INICIO - FIM DA ETAPA NO ANO LETIVO*/
    /* FAZ A BUSCA DA DATA DO PLANO DE AULA ENTRE ESSA DATA INICIO ATE O FIM */
    LEFT JOIN SMODETAPAPLETIVO (NOLOCK)
        ON SMODETAPAPLETIVO.IDPERLET = STURMADISC.IDPERLET
        AND SPLANOAULA.DATA BETWEEN SMODETAPAPLETIVO.DTINICIO AND SMODETAPAPLETIVO.DTFIM

    LEFT JOIN SFREQUENCIA
        ON SFREQUENCIA.IDTURMADISC = SPLANOAULA.IDTURMADISC
        AND SFREQUENCIA.DATA = SPLANOAULA.DATA
        AND SFREQUENCIA.RA = SMATRICPL.RA

    LEFT JOIN SALUNO (NOLOCK)
        ON SMATRICPL.RA = SALUNO.RA
        AND SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA
    
    LEFT JOIN SMATRICULA (NOLOCK)
        ON SALUNO.RA = SMATRICULA.RA 
        AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC 
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
        AND SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA 

    LEFT JOIN SPLETIVO (NOLOCK)
        ON SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA 
        AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET

    LEFT JOIN PPESSOA (NOLOCK) 
        ON SALUNO.CODPESSOA = PPESSOA.CODIGO

    LEFT JOIN SHORARIOTURMA
        ON SHORARIOTURMA.CODCOLIGADA = SPLANOAULA.CODCOLIGADA
        AND SHORARIOTURMA.IDHORARIOTURMA = SPLANOAULA.IDHORARIOTURMA

    LEFT JOIN SHORARIO
        ON SHORARIO.CODCOLIGADA = SHORARIOTURMA.CODCOLIGADA
        AND SHORARIO.CODHOR = SHORARIOTURMA.CODHOR


WHERE SPLETIVO.CODPERLET = :ANO_LETIVO
    AND SMATRICPL.CODCOLIGADA = :$COD_COLIGADA
    AND SMATRICPL.CODFILIAL = :COD_FILIAL
    AND SMATRICPL.CODTURMA LIKE Upper(:TURMA)
    AND STURMADISC.CODDISC LIKE Upper (:DISCIPLINA)
    AND SPLANOAULA.DATA BETWEEN :DATAINI AND :DATAFIM
    AND SMATRICPL.CODSTATUS = 1 /*MT no ano*/
    AND SMATRICULA.CODSTATUS = 1 /*MT na disciplina*/

GROUP BY 
    STURMADISC.CODDISC,
    SPLANOAULA.DATA,
    SHORARIO.HORAINICIAL,          
    SHORARIO.HORAFINAL,      
    SMATRICPL.RA,
    PPESSOA.NOME

ORDER BY 
    STURMADISC.CODDISC,
    SPLANOAULA.DATA,
    PPESSOA.NOME 